branch_change_webapp/branch_change_webapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin



#admin.site.index_template = 'admin/branch_chnge/change_form.html'
#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'branch_change_webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^$' , 'branch_change.views.login' , name = 'login'),

    url(r'^branch_change_form/', 'branch_change.views.branch_change_form', name='branch_change_form'),

    url(r'^login/$' , 'branch_change.views.login' , name = 'branch_change_form' ),

    url(r'^logout/$' , 'branch_change.views.logout' , name = 'branch_change_form' ),

    url(r'^authorized/' , 'branch_change.views.authorized_view' , name = 'authorized_view'),

    url(r'^register/' , 'branch_change.views.register' , name = 'register'),

    url(r'^naveen/' , 'branch_change.views.naveen' , name = 'user'),

    url(r'^download_csv/' , 'branch_change.views.download_csv' , name= 'branch_change_view'),

    url(r'^import_csv/' , 'branch_change.views.save_csv' , name = 'save' ),

    url(r'^get_allocation/' , 'branch_change.views.get_allocation' , name = 'output' ),

    url(r'^see_allocation/' , 'branch_change.views.see_allocation' , name='allo'),

    url(r'^see_stats/' , 'branch_change.views.see_stats' , name = 'stats'),
    
)



if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Branch Change \'15 Administration'

branch_change_webapp/branch_change/models.py
from django.db import models

# Create your models here.

class userpost(models.Model):
	ge='GE'
	obc='OBC'
	sc='SC'
	st='ST'
	
	CATEGORY_LIST = ((ge,ge),(obc,obc),(sc,sc),(st,st),)

	none = 'none'
	aebtech ='AE B.Tech'
	cebtech ='CE B.Tech'
	ch ='CH'
	clbtech ='CL B.Tech'
	cldualdeg ='CL Dual Deg'
	csbtech ='CS B.Tech'
	eebtech ='EE B.Tech'
	eedualdege1 ='EE Dual Deg E1'
	eedualdege2 ='EE Dual Deg E2'
	endualdeg ='EN Dual Deg'
	epbtech ='EP B.Tech'
	epdualdegn1 ='EP Dual Deg N1'
	mebtech ='ME B.Tech'
	medualdegm2 ='ME Dual Deg M2'
	mmbtech ='MM B.Tech'
	mmdualdegy1 ='MM Dual Deg Y1'
	mmdualdegy2 ='MM Dual Deg Y2'	

	BRANCH_LIST = (('',none),(aebtech,aebtech),(cebtech,cebtech),(ch,ch),(clbtech,clbtech),(cldualdeg,cldualdeg),(csbtech,csbtech),(eebtech,eebtech),(eedualdege1,eedualdege1),(eedualdege2,eedualdege2),(endualdeg,endualdeg),(epbtech,epbtech),(epdualdegn1,epdualdegn1),(mebtech,mebtech),(medualdegm2,medualdegm2),(mmbtech,mmbtech),(mmdualdegy1,mmdualdegy1),(mmdualdegy2,mmdualdegy2),)

	user_name = models.CharField(max_length = 100 , verbose_name = '')
	roll_number = models.CharField( max_length = 9 , verbose_name='Roll No')
	name = models.CharField( max_length = 100 ,verbose_name='Name')
	present_branch = models.CharField( max_length = 25 ,verbose_name='Present Branch', choices = BRANCH_LIST )
	category = models.CharField( max_length = 5 ,verbose_name='Category' , choices= CATEGORY_LIST , default = 'GE')
	cpi = models.DecimalField( max_digits = 5, decimal_places=2,verbose_name = 'CPI' )
	pref1 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 1' , choices = BRANCH_LIST )
	pref2 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 2' , choices = BRANCH_LIST , null = True , blank = True)
	pref3 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 3' , choices = BRANCH_LIST , null = True, blank = True)
	pref4 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 4' , choices = BRANCH_LIST , null = True, blank = True)
	pref5 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 5' , choices = BRANCH_LIST , null = True, blank = True)
	pref6 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 6' , choices = BRANCH_LIST , null = True, blank = True)
	pref7 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 7' , choices = BRANCH_LIST , null = True, blank = True)
	pref8 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 8' , choices = BRANCH_LIST, blank = True , null = True )
	pref9 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 9' , choices = BRANCH_LIST , blank = True, null = True )
	pref10 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 10' , choices = BRANCH_LIST, blank = True , null = True )
	pref11 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 11' , choices = BRANCH_LIST, blank = True , null = True )
	pref12 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 12' , choices = BRANCH_LIST, blank = True , null = True )
	pref13 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 13' , choices = BRANCH_LIST, blank = True , null = True )

	pref14 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 14' , choices = BRANCH_LIST , blank = True, null = True )
	pref15 = models.CharField( max_length = 25 , verbose_name = 'Wish to go to Pref 15' , choices = BRANCH_LIST, blank = True , null = True )


	def __str__(self):
		return self.user_name

'''
class loginpost(models.Model):
	username = models.CharField(max_length = 100 ,verbose_name='username')
	password = models.CharField(max_length = 100 ,verbose_name='password')
'''

# class adminfile(models.Model):
# 	file = models.FileField()

# 	def __str__(self):
# 		return self.file


class allocated_branch(models.Model):
	roll_number = models.CharField(max_length = 9,verbose_name='roll number')
	name = models.CharField(max_length = 100,verbose_name='name')
	initial_branch = models.CharField(max_length = 25,verbose_name='initial branch')
	alloted_branch = models.CharField(max_length = 25,verbose_name='alloted branch')

	def __str__(self):
		return self.roll_number

class branch_stats(models.Model):
	branch_name = models.CharField(max_length = 25,verbose_name='Branch Name')
	cutoff = models.CharField(max_length=10, verbose_name='Cutoff')
	sanctioned_st = models.CharField(max_length=10,verbose_name='Sanctioned Strength')
	original_st = models.CharField(max_length=10,verbose_name='Original Strength')
	final_st = models.CharField(max_length=10,verbose_name='Final Strength')

	def __str__(self):
		return self.branch_name

# class branch_stats(models.Model):
# 	branch_name = models.CharField(max_length = 25,verbose_name='Branch Name')
# 	cutoff = models.CharField(max_l=10, decimal_places=5, verbose_name='Cutoff')
# 	sanctioned_st = models.IntegerField(verbose_name='Sanctioned Strength')
# 	original_st = models.IntegerField(verbose_name='Original Strength')
# 	final_st = models.IntegerField(verbose_name='Final Strength')

# 	def __str__(self):
# 		return self.branch_name

branch_change_webapp/branch_change/views.py
from django.shortcuts import render

from django.core.urlresolvers import reverse
from django.http import HttpResponse

# Create your views here.
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf 

from django.contrib import messages
from django.template import RequestContext

from branch_change.forms import userpostform
from django.contrib.auth.forms import UserCreationForm
from branch_change.models import userpost

from branch_change.models import branch_stats
from branch_change.models import allocated_branch

import csv
import os
# from rest_framework.renderers import JSONRenderer
# from rest_framework.response import Response
# from rest_framework.views import APIView

def get_allocation(request):
	if not request.user.is_staff:
		raise PermissionDenied
	import subprocess
	#os.system("python3 ./export.csv ./input_programmes")
	subprocess.call("pwd",shell=True)
	subprocess.call("./main.sh",shell=True)
	subprocess.call("cd ..",shell=True)
	subprocess.call("pwd",shell=True)
	data = []
	with open('./branch_change/output.csv','r') as csvfile :
		reader = csv.reader(csvfile,delimiter = ',')
		for line in reader:
			input_data = allocated_branch()
			input_data.roll_number = line[0]
			input_data.name = line[1]
			input_data.initial_branch = line[2]
			input_data.alloted_branch = line[3]
			input_data.save()
	with open('./branch_change/output_stats.csv') as csvfile:
		reader = csv.reader(csvfile,delimiter = ',')
		for line in reader:
			input_data = branch_stats()
			input_data.branch_name = line[0]
			input_data.cutoff = line[1]
			input_data.sanctioned_st = line[2]
			input_data.original_st = line[3]
			input_data.final_st = line[4]
			input_data.save()
	return HttpResponseRedirect('/admin')


# def get_allocation(request):
# 	data = '<html><body><h1>Hello, world</h1></body></html>'
# 	return Response(data)

def save_csv(request):
	if not request.user.is_staff:
		raise PermissionDenied
	data = []
	with open('./branch_change/input_options.csv','r') as csvfile :
		reader = csv.reader(csvfile,delimiter = ',')
		for line in reader:
			input_data = userpost()
			input_data.user_name = '@'+line[0]+'__'
			input_data.roll_number = line[0]
			input_data.name = line[1]
			input_data.present_branch = line[2] 
			input_data.category = line[4]
			input_data.cpi = line[3]
			input_data.pref1 = line[5]
			input_data.pref2 = line[6]
			input_data.pref3 = line[7]
			input_data.pref4 = line[8]
			input_data.pref5 = line[9]
			input_data.pref6 = line[10]
			input_data.pref7 = line[11]
			input_data.pref8 = line[12]
			input_data.pref9 = line[13]
			input_data.pref10 = line[14]
			input_data.pref11= line[15]
			input_data.pref12 = line[16]
			input_data.pref13 = line[17]
			input_data.pref14 = line[18]
			input_data.pref15 = line[19]
			input_data.save()
	return HttpResponseRedirect('/admin')


def download_csv(request):
    if not request.user.is_staff:
        raise PermissionDenied
    queryset =userpost.objects.all()
    opts = queryset.model._meta
    model = queryset.model
    response = HttpResponse(content_type='text/csv')
    # force download.
    response['Content-Disposition'] = 'attachment;filename=export.csv'
    # the csv writer
    writer = csv.writer(response)
    field_names = [field.name for field in opts.fields]
    # Write a first row with header information
    writer.writerow(field_names)
    # Write data rows
    for obj in queryset:
        writer.writerow([getattr(obj, field) for field in field_names])
    return response
#download_csv.short_description = "Download selected as csv"

'''
def login(request):
	log={}
	log.update(csrf(request))
	return render_to_response('branch_change_form.html',log , context_instance = RequestContext(request))

'''		

'''
def branch_change_form(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		if request.method == 'POST':
			form = userpostform(request.POST)
			if form.is_valid():
				form.save()
				return HttpResponseRedirect('/naveen')
			else:
				print(form.errors)
		return render(request, 'branch_change_form.html', {'branch_change_form': userpostform() })
'''		
	



def branch_change_form(request):
   
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    try:
        queryset =userpost.objects.get(user_name = request.user.username)
    except:
        queryset = None

    if request.method == 'POST':
        form = userpostform(request.POST, instance = queryset)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/naveen')
        else:
            print(form.errors)
    else:
        try:
        	form = userpostform(initial = {'user_name':queryset.user_name,'roll_number' : queryset.roll_number , 'name' : queryset.name, 'cpi': queryset.cpi, 'present_branch' : queryset.present_branch, 'category': queryset.category, 'pref1': queryset.pref1, 'pref2': queryset.pref2, 'pref3': queryset.pref3, 'pref4': queryset.pref4, 'pref5': queryset.pref5, 'pref6': queryset.pref6, 'pref7': queryset.pref7, 'pref8': queryset.pref8, 'pref9': queryset.pref9, 'pref10': queryset.pref10, 'pref11': queryset.pref11, 'pref12': queryset.pref12, 'pref13': queryset.pref13, 'pref14': queryset.pref14, 'pref15': queryset.pref15 })
        except:
        	form = userpostform(initial = {'user_name':request.user.username })
    context = {
     'branch_change_form' :form,
     'queryset' :queryset

    }
    return render(request, 'branch_change_form.html', context)
    #return render(request, 'user.html', context)


def login(request):
	if not request.user.is_authenticated():
		log={}
		log.update(csrf(request))
		return render_to_response('branch_change_form.html',log , context_instance = RequestContext(request))
	else:
		return HttpResponseRedirect('/branch_change_form')


def logout(request):
	auth.logout(request)
	render_to_response('branch_change_form.html',{})
	return HttpResponseRedirect('/login')

def authorized_view(request):
	username = request.POST.get('username','')
	password = request.POST.get('password', '')
	user = auth.authenticate(username=username, password =password )

	if user is not None:
		auth.login(request,user)
		return HttpResponseRedirect('/branch_change_form')
	else:
		messages.error(request, 'username or password is not valid')
		return HttpResponseRedirect('/login')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/branch_change_form")
    args = {}
    args.update(csrf(request))

    args['form'] = UserCreationForm()

    return render_to_response('registration.html',args)

def naveen(request):
	try:
		queryset =userpost.objects.get(user_name = request.user.username)
	except:
		queryset = None
	context = {
    	'queryset' :queryset
    }
	return render(request, 'user.html', context)

def see_allocation(request):
	if not request.user.is_staff:
		raise PermissionDenied
	try:
		queryset = allocated_branch.objects.all()
	except:
		queryset = None
	context = {
		'queryset' :queryset
		}
	return render(request, 'get_allocation.html' , context)


def see_stats(request):
	if not request.user.is_staff:
		raise PermissionDenied
	try:
		queryset = branch_stats.objects.all()
	except:
		queryset = None
	context = {
		'queryset' :queryset
		}
	return render(request, 'get_stats.html' , context)

branch_change_webapp/branch_change/templates/branch_change_head.html
{% load staticfiles %}
<head>
<title>Branch Change For 2015</title>
<!-- Bootstap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
<!-- jQuery library -->
<script src="{% static 'js/jquery.js' %}"></script>
<!-- Latest compiled JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Input Validation Java Script -->

<!-- Dynamic prefernce -->
<script src= "{% static 'js/dynamicadd.js' %}"></script>

<script src = "{% static 'css/bootstrapvalidator.css' %}"> </script>
<script src = "{% static 'js/bootstrapvalidator.js' %}" > </script>

<script type="text/javascript">
    var mm={{user.username}}

</script>


<script>

$(document).ready(function() {
    $('#branchForm').bootstrapValidator({
        
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields:{
        	roll_number:{
        		validators:{
        			notEmpty:{
        				message: 'Roll No can not be empty'
        			},
        			stringLength:{
        				min: 9,
        				max: 9,
        				message: 'Roll No should be of 9 digits'
        			},
        			regexp:{
        				regexp: /^[15]{2,2}[D0-9]{1,1}[0-9]{6,6}/,
        				message: 'Valid Roll No: 15XXXXXXX'
        			}
        			
        		}
        	},
        	cpi:{
        		validators:{
        			notEmpty:{
        				message: 'CPI must be in [0,10] only'
        			},
        			between:{
        				min: 0,
        				max: 10,
        				message: 'CPI must be in [0,10] only'
        			},
        			stringLength:{
        				min: 1,
        				max: 5,
        				message: 'only two digits after decimal places allowed'
        			}
        		}
        	},
        	name:{
        		validators:{
        			notEmpty:{
        				message: 'name can not be empty'
        			},
                    regexp:{
                        regexp: /^[a-zA-Z ]*$/,
                        message: 'name can contain only a-z and A-Z'
                    }
        		}
        	},
            present_branch:{
                validators:{
                    notEmpty:{
                        message:'present branch cant be empty'
                    }
                }
            },
            pref1:{
                validators:{
                    notEmpty:{
                        message:'preference 1 can not be empty'
                    },
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref2:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref3:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref4:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref5:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref6:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref7:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref8:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref9:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref10:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref11:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref12:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref13:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref14:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            },
            pref15:{
                validators:{
                    different:{
                        field:'present_branch',
                        message: 'present branch and prefernce must be different'
                    }

                }
            }
            
        }


    });

	 

});




</script>


<script>
    /*$(document).on('change',"#pref1",function(){
            if($.trim($("#pref1").val()) == '')
            {
                $("#pref2").css({"display","none"});
            }
        });
    });    */
$(document).ready(function(){
var maxpreference=15;
var counter=1;
var e=2;
for(e=2;e<=15;e++){
    if(($("#id_pref"+e).val())=='')
    {break;}
}
for(var xx=e+1;xx<=15;xx++)
{
    $("#Pref"+xx).css("display","none");
}


$(document).on('change',"#id_pref1",function(){
        if(($("#id_pref1").val())=='')
        {
            for(var i =2 ; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                 $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref2").css("display","block");
}
});

$(document).on('change',"#id_pref2",function(){
        if(($("#id_pref2").val())=='')
        {
            for(var i =3; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref3").css("display","block");
}
});

$(document).on('change',"#id_pref3",function(){
        if(($("#id_pref3").val())=='')
        {
            for(var i =4; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref4").css("display","block");
}
});

$(document).on('change',"#id_pref4",function(){
        if(($("#id_pref4").val())=='')
        {
            for(var i =5 ; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref5").css("display","block");
}
});

$(document).on('change',"#id_pref5",function(){
        if(($("#id_pref5").val())=='')
        {
            for(var i =6; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref6").css("display","block");
}
});

$(document).on('change',"#id_pref6",function(){
        if(($("#id_pref6").val())=='')
        {
            for(var i =7; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref7").css("display","block");
}
});

$(document).on('change',"#id_pref7",function(){
        if(($("#id_pref7").val())=='')
        {
            for(var i =8; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref8").css("display","block");
}
});

$(document).on('change',"#id_pref8",function(){
        if(($("#id_pref8").val())=='')
        {
            for(var i =9; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref9").css("display","block");
}
});

$(document).on('change',"#id_pref9",function(){
        if(($("#id_pref9").val())=='')
        {
            for(var i =10; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref10").css("display","block");
}
});

$(document).on('change',"#id_pref10",function(){
        if(($("#id_pref10").val())=='')
        {
            for(var i =11; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref11").css("display","block");
}
});

$(document).on('change',"#id_pref11",function(){
        if(($("#id_pref11").val())=='')
        {
            for(var i =12 ; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref12").css("display","block");
}
});

$(document).on('change',"#id_pref12",function(){
        if(($("#id_pref12").val())=='')
        {
            for(var i =13 ; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref13").css("display","block");
}
});

$(document).on('change',"#id_pref13",function(){
        if(($("#id_pref13").val())=='')
        {
            for(var i =14 ; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref14").css("display","block");
}
});

$(document).on('change',"#id_pref14",function(){
        if(($("#id_pref14").val())=='')
        {
            for(var i =15; i<=15;i++)
            {
                var t = i.toString();
                $("#id_pref" + t).val('');
                $("#Pref"+t).css("display","none");

            }
        
    }

else{
    $("#Pref15").css("display","block");
}
});






});




</script>


<script>
    
$(document).ready(function(){
    $("#id_cpi").change(function(){
        if(($("#id_category").val())=='GE' || ($("#id_category").val())=='OBC'){
        if(($("#id_cpi").val())<8){
        alert("Your CPI is less than 8 and you might not get a branch change");}
}
    else{
        if(($("#id_cpi").val())<7){
        alert("Your CPI is less than 7 and you might not get a branch change");}
}
    });
});


</script>

</head>

branch_change_webapp/branch_change/templates/get_allocation.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">

{% include 'branch_change_head.html' %}

<style>
table {
    width:100%;
}
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
table#t01 tr:nth-child(even) {
    background-color: #eee;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th  {
    background-color: black;
    color: white;
}
</style>

<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                
      </button>
      <a class="navbar-brand">Branch Change '15 Administration Final Branch Allocation</a>
    </div>


    <div class="collapse navbar-collapse" id="myNavbar">
      
      <ul class="nav navbar-nav navbar-right">

<li><a href="/admin"><span class="glyphicon glyphicon-left-arrow"></span> Admin</a></li>



      </ul>
    </div>
  </div>


</nav>


{% if queryset %}
            


<table>
  <tr>
    <th>Roll Number</th>
    <th>Name</th>    
    <th>Initial Branch</th>
    <th>Final Branch</th>
  </tr>
 
  {% for x in queryset %}
  <tr>
  <th>{{ x.roll_number }}</th>
  <th>{{ x.name }}</th>
  <th>{{ x.initial_branch }}</th>
  <th>{{ x.alloted_branch }}</th>
  
  {% endfor %}

</table>

 {% endif %}



&copy /inficoders\
</body>
</html>